prompt_steps:
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。现在，你的队员正在案发现场仓库进行调查。而你，正通过监控远程查看队员们的调查情况。队员们会把一些他们认为重要的，在案发现场找到的物品线索展示给你，你可以根据这些物品线索推测凶手的作案方式，以及凶手究竟是什么样的人，也可以单纯对线索进行描述。
    conds:
      - - 烟头
      - - 会员卡
      - - 手串
    welcome_info: 各位调查员你们好，我是朝阳市刑侦大队第一支队的队长李伟。近期，我市发生一系列针对于二次元女生的连环凶杀案，性质及其恶劣。你们现在所在的位置，就是最近一位受害者被发现的案发现场。今天早上，保洁阿姨张芳丽向我们报案。目前，尸体已经被移交到法医这里，尸检结果随后也会发给你们。现在，请你们对案发现场进行调查，我们通过摄像头远程对你们进行协助。如果你们找到觉得可疑的物品或线索，可疑把它放到摄像头下，让我更清楚的看到它。但也请注意，对证物要轻拿轻放，千万不要破坏现场证物。
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。你的队员们也对案发现场进行了勘察。在案发现场，队员们发现了半支烟头与一个手串，还找到了一张"正心馆"的会员卡。现在，你的队员们正在正心馆跆拳道馆进行调查。而你，正通过监控远程查看队员们的调查情况。队员们会把一些他们认为重要的，在正心馆找到的物品线索展示给你，你可以根据这些物品线索推测凶手的作案方式，以及凶手究竟是什么样的人，也可以单纯对线索进行描述。
    conds:
      - - 前台工作人员
      - - 双节棍
      - - 会员登记表
    welcome_info: 各位调查员，看来，你们已经对现场进行了仔细的勘察，你们找到了很重要的线索。凶手可能吸烟，可能在现场遗落了自己的手串，正心馆这个地方也很可疑。接下来，请各位前往正心馆调查，并让我看到正心馆里有哪些可疑的线索。
  - prompt: 你是朝阳市刑侦大队第一支队的队长李伟，最近，你正在调查一起发生在朝阳市内，针对于二次元女生的连环凶杀案。就在前天，又有一名喜欢二次元的女生死在了"北投潮街"的一间仓库里。你的队员们也对案发现场进行了勘察，又发现了前台工作人员，双节棍，会员登记表这三个线索，现在，你需要根据这些线索，推断凶手的作案方式以及凶手的具体情况。
    conds: []
    welcome_info: 如果你们已经对正心馆调查的差不多了，可以回到调查室。根据你们刚刚调查的结果，指认你们认为最有可能是凶手的人！

use_record_images: false
record_image_threshold: 0.85

items:
  - name: 烟头
    img_path: asset/images/烟头.jpg
    text: 现场找到了烟头...? 你们先收好，随后把它交给助理警员，我们会对这个烟头进行检查，看看上面是否存在嫌疑人的DNA。
  - name: 油漆桶
    img_path: asset/images/油漆桶.jpg
    text: 根据商场提供的信息，这个油漆桶已经放在这里很久了，是之前装修时遗留的。
  - name: 会员卡
    img_path: asset/images/会员卡.jpg
    text: 这是"正心馆"的会员卡？据调查，死者并没有办过正心馆的会员，难道，这是凶手行凶时不小心掉落的？这是个值得调查的突破口。
  - name: 手串
    img_path: asset/images/手串.jpg
    text: 这个手串看起来有点年头了，被害人是个小姑娘，肯定不是被害人的。如果它属于凶手，那凶手一定是个上了年纪的男人。
  - name: 一张人脸
    img_path: asset/images/人脸.jpg
    text: 这是案发现场的尸体吗？不对啊，我们已经将尸体带到法医这里了... 啊不好意思，我看错了，原来这是你们的脸，我的调查员们，面色略显苍白啊。
  - name: 前台工作人员
    img_path: asset/images/前台工作人员.jpg
    text: 这位应该就是正心馆的工作人员了，请您配合我们的调查。各位队员，你们也可以向他询问案发时的情况，了解更多线索。
  - name: 双节棍
    img_path: asset/images/双节棍.jpg
    text: 经过法医鉴定，被害的女生也是被钝器砸死的，但现在还没有找到凶器。不知这双节棍是否可以成为凶器？
  - name: 会员登记表
    img_path: asset/images/会员登记表.jpg
    text: 你们可以仔细研究一下这个会员登记表，并询问一下前台工作人员，这里面有没有喜欢带手串，吸烟的中年男人。
  - name: 什么都没有的背景图
    img_path: local_data/base_image/什么都没有的背景图_w7Sm0JPZ.jpg
    text: 各位警员，请抓紧调查，把你们觉得可疑的现场物品放在摄像头下。不要浪费勘察的机会。
  - name: 一瓶可乐
    img_path: local_data/base_image/一瓶雪碧_i2pzxcXO.jpg
    text: 这是一个可乐易拉罐。昨天我们在询问死者同事过程中了解到，死者之前很爱喝可乐，经常偷偷把电影院前台饮料机里的可乐装进大水壶里带回家，还因此被扣过钱。仓库里出现可乐倒也正常... 但有没有可能，是凶手用可乐把死者吸引到仓库，死者完全沉迷在可乐带来的愉悦之中，没有防备，然后被凶手得逞了呢？
  - name: 一瓶保健品
    img_path: local_data/base_image/一瓶保健品_v1CjL1cI.jpg
    text: 现场有个药瓶... 根据尸检报告，死者是被斧头砍死的，这个药瓶会与案件有哪些联系呢？难道说，凶手预先知道了死者的服药习惯，然后偷偷替换了死者常用的药，死者先因服药晕了过去，失去抵抗能力之后凶手才作案的？不管怎，先把药瓶先收好，带回来检查一下指纹以及里面残留的药物。
  - name: 手机
    img_path: local_data/base_image/手机.jpg
    text: 一部坏了的手机，这应该是死者的，已经完全无法使用了。不知它是在死者与凶手搏斗过程中被损坏的，还是凶手作案后故意损坏的。如果是后者，手机里一定有重要的线索。后续调查中，我们会使用技术手段尝试还原手机里的资料，看看凶手究竟想销毁哪些证据。
  - name: 笔
    img_path: local_data/base_image/笔.jpg
    text: 现场怎么会有一支笔呢？死者临终前有用这支笔写过什么东西么？这值得调查。
  - name: 钱包
    img_path: local_data/base_image/钱包.jpg
    text: 经调查，这个钱包属于死者的同事孔舟，他的钱包为什么会留在现场呢？快打开看看里面有什么东西。孔舟这个人，也值得进一步调查。




